app.exe:    app.cs  basketballplayer.dll
    csc /t:exe /out:app.exe app.cs /r:basketballplayer.dll

basketballplayer.dll:   basketballplayer.cs
    csc /t:library  /out: basketballplayer.dll basketballplayer.cs

clean:
    del *.dll
    del *.exe